# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsclassmodel',
            options={'verbose_name': '商品分类表', 'verbose_name_plural': '商品分类表'},
        ),
        migrations.AlterModelOptions(
            name='goodsskumodel',
            options={'verbose_name': '商品SKU表', 'verbose_name_plural': '商品SKU表'},
        ),
        migrations.AlterModelOptions(
            name='goodsspumodel',
            options={'verbose_name': '商品SPU表', 'verbose_name_plural': '商品SPU表'},
        ),
        migrations.AlterModelOptions(
            name='photoalbummodel',
            options={'verbose_name': '商品相册表', 'verbose_name_plural': '商品相册表'},
        ),
        migrations.AlterModelOptions(
            name='unitmodel',
            options={'verbose_name': '商品单位表', 'verbose_name_plural': '商品单位表'},
        ),
        migrations.AlterModelTable(
            name='goodsclassmodel',
            table='GoodsClassModel',
        ),
        migrations.AlterModelTable(
            name='goodsskumodel',
            table='GoodsSKUModel',
        ),
        migrations.AlterModelTable(
            name='goodsspumodel',
            table='GoodsSPUModel',
        ),
        migrations.AlterModelTable(
            name='photoalbummodel',
            table='PhotoAlbumModel',
        ),
        migrations.AlterModelTable(
            name='unitmodel',
            table='UnitModel',
        ),
    ]
