# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 22:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190122_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsskumodel',
            old_name='head',
            new_name='goodslogo',
        ),
        migrations.AlterField(
            model_name='goodsclassmodel',
            name='classbrief',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='分类简介'),
        ),
        migrations.AlterField(
            model_name='goodsclassmodel',
            name='classname',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='goodsskumodel',
            name='goodsbrief',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='goodsskumodel',
            name='goodsclass_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsClassModel', verbose_name='商品分类ID'),
        ),
        migrations.AlterField(
            model_name='goodsskumodel',
            name='goodsname',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='goodsskumodel',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goodsskumodel',
            name='sales',
            field=models.PositiveIntegerField(verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='goodsskumodel',
            name='shelves',
            field=models.SmallIntegerField(choices=[(0, '未上架'), (1, '已上架')], verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='goodsskumodel',
            name='spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSPUModel', verbose_name='商品spu_id'),
        ),
        migrations.AlterField(
            model_name='goodsskumodel',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='goodsskumodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.UnitModel', verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='goodsspumodel',
            name='SPUdetails',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='spu详情'),
        ),
        migrations.AlterField(
            model_name='goodsspumodel',
            name='SPUname',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='spu名称'),
        ),
        migrations.AlterField(
            model_name='photoalbummodel',
            name='goodsSKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKUModel', verbose_name='商品SKU'),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='unitname',
            field=models.CharField(max_length=10, verbose_name='单位名'),
        ),
    ]
