# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 11:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190122_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsskumodel',
            name='goodslogo',
            field=models.ImageField(upload_to='goodslogo/%y%m/%d', verbose_name='商品logo'),
        ),
        migrations.AlterField(
            model_name='goodsspumodel',
            name='SPUdetails',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='spu详情'),
        ),
    ]
