# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='head',
            field=models.FileField(default='images/favicon.png', upload_to='images'),
        ),
    ]
