# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='birthday',
            field=models.DateField(auto_now_add=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='head',
            field=models.ImageField(default='user/201901/21/favicon.png', upload_to='user/%y%m/%d', verbose_name='头像'),
        ),
    ]
