# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodels_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='性别'),
        ),
    ]
